# Generated by Django 3.2.25 on 2025-11-03 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0067_auto_20201230_1237'),
        ('userstories', '0021_auto_20201202_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepoints',
            name='points',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='role_points', to='projects.points', verbose_name='points'),
            preserve_default=False,
        ),
    ]
