# Generated by Django 3.2.25 on 2025-11-04 07:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0067_auto_20201230_1237'),
        ('userstories', '0022_alter_rolepoints_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='HR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField(blank=True, default=None)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
                ('finish_date', models.DateTimeField(blank=True, null=True, verbose_name='finish date')),
                ('hr_name', models.TextField(blank=True, default=None)),
                ('file_url', models.URLField(blank=True, default=None)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_docs', to='projects.project', verbose_name='project')),
            ],
        ),
    ]
